on: [push]
name: Azure ARM
jobs:
  Iot-Lab-Deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

    - name: Azure Login
      uses: Azure/cli@v1
      with:
        # Specify the script here
        inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_AD_CLIENT_ID }} -p ${{ secrets.AZURE_AD_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_AD_TENANT_ID }}
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy_RG
      uses: Azure/cli@v1
      with:
        # Specify the script here
        inlineScript: |
          az deployment sub create \
          --name demoSubDeployment \
          --location eastus \
          --template-file ./bicep/iac/modules/resourcegroup.bicep

    - name: Deploy_EdgeDevices
      uses: Azure/cli@v1
      with:
        # Specify the script here
        inlineScript: az deployment group create --resource-group iotlab-101 --template-file ./bicep/iac/device_base-env.bicep
