on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
    # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
       creds: ${{ secrets.AZURE_SUBSCRIPTION }}

    # deploy bicep
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ansible-test
        template: ./bicep/iac/device_base-env.bicep
        failOnStdErr: false
